openapi: 3.1.0
info:
  version: 1.0.0
  title: Water traker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Water traker website
tags:
  - name: Water traker
    description: Operations about Water traker.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://watertraker-backend.onrender.com
  - url: https://watertraker-backend.onrender.com/api/auth
paths:
  /signup:
    post:
      $ref: "../swagger/paths/signup/post.yaml"
  /signin:
    post:
      $ref: "../swagger/paths/signin/post.yaml"
  /signout:
    post:
      $ref: "../swagger/paths/signout/post.yaml"
  /current:
    get:
      $ref: "../swagger/paths/current-user/get.yaml"
  /user:
    get:
      $ref: "../swagger/paths/user/get.yaml"
    patch:
      $ref: "../swagger/paths/user/userPatch.yaml"
  /avatar:
    post:
      $ref: "../swagger/paths/user/post.yaml"
    patch:
      $ref: "../swagger/paths/user/patch.yaml"
  /water-rate:
    patch:
      $ref: "../swagger/paths/user/waterRatePatch.yaml"
  /water:
    get:
      $ref: "../swagger/paths/water/get.yaml"
    post:
      $ref: "../swagger/paths/water/post.yaml"
  /water/{id}:
    get:
      $ref: "../swagger/paths/water/getById.yaml"
    put:
      $ref: "../swagger/paths/water/put.yaml"
    delete:
      $ref: "../swagger/paths/water/delete.yaml"
  /water/month/{id}:
    get:
      $ref: "../swagger/paths/water/getMothById.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
